package net.minecraft.tag;

import net.minecraft.block.Block;
import net.minecraft.util.registry.Registry;

public final class BlockTags {
   protected static final RequiredTagList<Block> REQUIRED_TAGS;
   public static final Tag.Identified<Block> WOOL;
   public static final Tag.Identified<Block> PLANKS;
   public static final Tag.Identified<Block> STONE_BRICKS;
   public static final Tag.Identified<Block> WOODEN_BUTTONS;
   public static final Tag.Identified<Block> BUTTONS;
   public static final Tag.Identified<Block> CARPETS;
   public static final Tag.Identified<Block> WOODEN_DOORS;
   public static final Tag.Identified<Block> WOODEN_STAIRS;
   public static final Tag.Identified<Block> WOODEN_SLABS;
   public static final Tag.Identified<Block> WOODEN_FENCES;
   public static final Tag.Identified<Block> PRESSURE_PLATES;
   public static final Tag.Identified<Block> WOODEN_PRESSURE_PLATES;
   public static final Tag.Identified<Block> STONE_PRESSURE_PLATES;
   public static final Tag.Identified<Block> WOODEN_TRAPDOORS;
   public static final Tag.Identified<Block> DOORS;
   public static final Tag.Identified<Block> SAPLINGS;
   public static final Tag.Identified<Block> LOGS_THAT_BURN;
   public static final Tag.Identified<Block> LOGS;
   public static final Tag.Identified<Block> DARK_OAK_LOGS;
   public static final Tag.Identified<Block> OAK_LOGS;
   public static final Tag.Identified<Block> BIRCH_LOGS;
   public static final Tag.Identified<Block> ACACIA_LOGS;
   public static final Tag.Identified<Block> JUNGLE_LOGS;
   public static final Tag.Identified<Block> SPRUCE_LOGS;
   public static final Tag.Identified<Block> CRIMSON_STEMS;
   public static final Tag.Identified<Block> WARPED_STEMS;
   public static final Tag.Identified<Block> BANNERS;
   public static final Tag.Identified<Block> SAND;
   public static final Tag.Identified<Block> STAIRS;
   public static final Tag.Identified<Block> SLABS;
   public static final Tag.Identified<Block> WALLS;
   public static final Tag.Identified<Block> ANVIL;
   public static final Tag.Identified<Block> RAILS;
   public static final Tag.Identified<Block> LEAVES;
   public static final Tag.Identified<Block> TRAPDOORS;
   public static final Tag.Identified<Block> SMALL_FLOWERS;
   public static final Tag.Identified<Block> BEDS;
   public static final Tag.Identified<Block> FENCES;
   public static final Tag.Identified<Block> TALL_FLOWERS;
   public static final Tag.Identified<Block> FLOWERS;
   public static final Tag.Identified<Block> PIGLIN_REPELLENTS;
   public static final Tag.Identified<Block> GOLD_ORES;
   public static final Tag.Identified<Block> IRON_ORES;
   public static final Tag.Identified<Block> DIAMOND_ORES;
   public static final Tag.Identified<Block> REDSTONE_ORES;
   public static final Tag.Identified<Block> LAPIS_ORES;
   public static final Tag.Identified<Block> COAL_ORES;
   public static final Tag.Identified<Block> EMERALD_ORES;
   public static final Tag.Identified<Block> COPPER_ORES;
   public static final Tag.Identified<Block> NON_FLAMMABLE_WOOD;
   public static final Tag.Identified<Block> CANDLES;
   public static final Tag.Identified<Block> DIRT;
   public static final Tag.Identified<Block> FLOWER_POTS;
   public static final Tag.Identified<Block> ENDERMAN_HOLDABLE;
   public static final Tag.Identified<Block> ICE;
   public static final Tag.Identified<Block> VALID_SPAWN;
   public static final Tag.Identified<Block> IMPERMEABLE;
   public static final Tag.Identified<Block> UNDERWATER_BONEMEALS;
   public static final Tag.Identified<Block> CORAL_BLOCKS;
   public static final Tag.Identified<Block> WALL_CORALS;
   public static final Tag.Identified<Block> CORAL_PLANTS;
   public static final Tag.Identified<Block> CORALS;
   public static final Tag.Identified<Block> BAMBOO_PLANTABLE_ON;
   public static final Tag.Identified<Block> STANDING_SIGNS;
   public static final Tag.Identified<Block> WALL_SIGNS;
   public static final Tag.Identified<Block> SIGNS;
   public static final Tag.Identified<Block> DRAGON_IMMUNE;
   public static final Tag.Identified<Block> WITHER_IMMUNE;
   public static final Tag.Identified<Block> WITHER_SUMMON_BASE_BLOCKS;
   public static final Tag.Identified<Block> BEEHIVES;
   public static final Tag.Identified<Block> CROPS;
   public static final Tag.Identified<Block> BEE_GROWABLES;
   public static final Tag.Identified<Block> PORTALS;
   public static final Tag.Identified<Block> FIRE;
   public static final Tag.Identified<Block> NYLIUM;
   public static final Tag.Identified<Block> WART_BLOCKS;
   public static final Tag.Identified<Block> BEACON_BASE_BLOCKS;
   public static final Tag.Identified<Block> SOUL_SPEED_BLOCKS;
   public static final Tag.Identified<Block> WALL_POST_OVERRIDE;
   public static final Tag.Identified<Block> CLIMBABLE;
   public static final Tag.Identified<Block> SHULKER_BOXES;
   public static final Tag.Identified<Block> HOGLIN_REPELLENTS;
   public static final Tag.Identified<Block> SOUL_FIRE_BASE_BLOCKS;
   public static final Tag.Identified<Block> STRIDER_WARM_BLOCKS;
   public static final Tag.Identified<Block> CAMPFIRES;
   public static final Tag.Identified<Block> GUARDED_BY_PIGLINS;
   public static final Tag.Identified<Block> PREVENT_MOB_SPAWNING_INSIDE;
   public static final Tag.Identified<Block> FENCE_GATES;
   public static final Tag.Identified<Block> UNSTABLE_BOTTOM_CENTER;
   public static final Tag.Identified<Block> MUSHROOM_GROW_BLOCK;
   public static final Tag.Identified<Block> INFINIBURN_OVERWORLD;
   public static final Tag.Identified<Block> INFINIBURN_NETHER;
   public static final Tag.Identified<Block> INFINIBURN_END;
   public static final Tag.Identified<Block> BASE_STONE_OVERWORLD;
   public static final Tag.Identified<Block> STONE_ORE_REPLACEABLES;
   public static final Tag.Identified<Block> DEEPSLATE_ORE_REPLACEABLES;
   public static final Tag.Identified<Block> BASE_STONE_NETHER;
   public static final Tag.Identified<Block> CANDLE_CAKES;
   public static final Tag.Identified<Block> CAULDRONS;
   public static final Tag.Identified<Block> CRYSTAL_SOUND_BLOCKS;
   public static final Tag.Identified<Block> INSIDE_STEP_SOUND_BLOCKS;
   public static final Tag.Identified<Block> OCCLUDES_VIBRATION_SIGNALS;
   public static final Tag.Identified<Block> DRIPSTONE_REPLACEABLE_BLOCKS;
   public static final Tag.Identified<Block> CAVE_VINES;
   public static final Tag.Identified<Block> MOSS_REPLACEABLE;
   public static final Tag.Identified<Block> LUSH_GROUND_REPLACEABLE;
   public static final Tag.Identified<Block> SMALL_DRIPLEAF_PLACEABLE;
   public static final Tag.Identified<Block> SNOW;
   public static final Tag.Identified<Block> AXE_MINEABLE;
   public static final Tag.Identified<Block> HOE_MINEABLE;
   public static final Tag.Identified<Block> PICKAXE_MINEABLE;
   public static final Tag.Identified<Block> SHOVEL_MINEABLE;
   public static final Tag.Identified<Block> NEEDS_DIAMOND_TOOL;
   public static final Tag.Identified<Block> NEEDS_IRON_TOOL;
   public static final Tag.Identified<Block> NEEDS_STONE_TOOL;
   public static final Tag.Identified<Block> FEATURES_CANNOT_REPLACE;
   public static final Tag.Identified<Block> LAVA_POOL_STONE_REPLACEABLES;
   public static final Tag.Identified<Block> GEODE_INVALID_BLOCKS;

   private BlockTags() {
   }

   private static Tag.Identified<Block> register(String id) {
      return REQUIRED_TAGS.add(id);
   }

   public static TagGroup<Block> getTagGroup() {
      return REQUIRED_TAGS.getGroup();
   }

   static {
      REQUIRED_TAGS = RequiredTagListRegistry.register(Registry.BLOCK_KEY, "tags/blocks");
      WOOL = register("wool");
      PLANKS = register("planks");
      STONE_BRICKS = register("stone_bricks");
      WOODEN_BUTTONS = register("wooden_buttons");
      BUTTONS = register("buttons");
      CARPETS = register("carpets");
      WOODEN_DOORS = register("wooden_doors");
      WOODEN_STAIRS = register("wooden_stairs");
      WOODEN_SLABS = register("wooden_slabs");
      WOODEN_FENCES = register("wooden_fences");
      PRESSURE_PLATES = register("pressure_plates");
      WOODEN_PRESSURE_PLATES = register("wooden_pressure_plates");
      STONE_PRESSURE_PLATES = register("stone_pressure_plates");
      WOODEN_TRAPDOORS = register("wooden_trapdoors");
      DOORS = register("doors");
      SAPLINGS = register("saplings");
      LOGS_THAT_BURN = register("logs_that_burn");
      LOGS = register("logs");
      DARK_OAK_LOGS = register("dark_oak_logs");
      OAK_LOGS = register("oak_logs");
      BIRCH_LOGS = register("birch_logs");
      ACACIA_LOGS = register("acacia_logs");
      JUNGLE_LOGS = register("jungle_logs");
      SPRUCE_LOGS = register("spruce_logs");
      CRIMSON_STEMS = register("crimson_stems");
      WARPED_STEMS = register("warped_stems");
      BANNERS = register("banners");
      SAND = register("sand");
      STAIRS = register("stairs");
      SLABS = register("slabs");
      WALLS = register("walls");
      ANVIL = register("anvil");
      RAILS = register("rails");
      LEAVES = register("leaves");
      TRAPDOORS = register("trapdoors");
      SMALL_FLOWERS = register("small_flowers");
      BEDS = register("beds");
      FENCES = register("fences");
      TALL_FLOWERS = register("tall_flowers");
      FLOWERS = register("flowers");
      PIGLIN_REPELLENTS = register("piglin_repellents");
      GOLD_ORES = register("gold_ores");
      IRON_ORES = register("iron_ores");
      DIAMOND_ORES = register("diamond_ores");
      REDSTONE_ORES = register("redstone_ores");
      LAPIS_ORES = register("lapis_ores");
      COAL_ORES = register("coal_ores");
      EMERALD_ORES = register("emerald_ores");
      COPPER_ORES = register("copper_ores");
      NON_FLAMMABLE_WOOD = register("non_flammable_wood");
      CANDLES = register("candles");
      DIRT = register("dirt");
      FLOWER_POTS = register("flower_pots");
      ENDERMAN_HOLDABLE = register("enderman_holdable");
      ICE = register("ice");
      VALID_SPAWN = register("valid_spawn");
      IMPERMEABLE = register("impermeable");
      UNDERWATER_BONEMEALS = register("underwater_bonemeals");
      CORAL_BLOCKS = register("coral_blocks");
      WALL_CORALS = register("wall_corals");
      CORAL_PLANTS = register("coral_plants");
      CORALS = register("corals");
      BAMBOO_PLANTABLE_ON = register("bamboo_plantable_on");
      STANDING_SIGNS = register("standing_signs");
      WALL_SIGNS = register("wall_signs");
      SIGNS = register("signs");
      DRAGON_IMMUNE = register("dragon_immune");
      WITHER_IMMUNE = register("wither_immune");
      WITHER_SUMMON_BASE_BLOCKS = register("wither_summon_base_blocks");
      BEEHIVES = register("beehives");
      CROPS = register("crops");
      BEE_GROWABLES = register("bee_growables");
      PORTALS = register("portals");
      FIRE = register("fire");
      NYLIUM = register("nylium");
      WART_BLOCKS = register("wart_blocks");
      BEACON_BASE_BLOCKS = register("beacon_base_blocks");
      SOUL_SPEED_BLOCKS = register("soul_speed_blocks");
      WALL_POST_OVERRIDE = register("wall_post_override");
      CLIMBABLE = register("climbable");
      SHULKER_BOXES = register("shulker_boxes");
      HOGLIN_REPELLENTS = register("hoglin_repellents");
      SOUL_FIRE_BASE_BLOCKS = register("soul_fire_base_blocks");
      STRIDER_WARM_BLOCKS = register("strider_warm_blocks");
      CAMPFIRES = register("campfires");
      GUARDED_BY_PIGLINS = register("guarded_by_piglins");
      PREVENT_MOB_SPAWNING_INSIDE = register("prevent_mob_spawning_inside");
      FENCE_GATES = register("fence_gates");
      UNSTABLE_BOTTOM_CENTER = register("unstable_bottom_center");
      MUSHROOM_GROW_BLOCK = register("mushroom_grow_block");
      INFINIBURN_OVERWORLD = register("infiniburn_overworld");
      INFINIBURN_NETHER = register("infiniburn_nether");
      INFINIBURN_END = register("infiniburn_end");
      BASE_STONE_OVERWORLD = register("base_stone_overworld");
      STONE_ORE_REPLACEABLES = register("stone_ore_replaceables");
      DEEPSLATE_ORE_REPLACEABLES = register("deepslate_ore_replaceables");
      BASE_STONE_NETHER = register("base_stone_nether");
      CANDLE_CAKES = register("candle_cakes");
      CAULDRONS = register("cauldrons");
      CRYSTAL_SOUND_BLOCKS = register("crystal_sound_blocks");
      INSIDE_STEP_SOUND_BLOCKS = register("inside_step_sound_blocks");
      OCCLUDES_VIBRATION_SIGNALS = register("occludes_vibration_signals");
      DRIPSTONE_REPLACEABLE_BLOCKS = register("dripstone_replaceable_blocks");
      CAVE_VINES = register("cave_vines");
      MOSS_REPLACEABLE = register("moss_replaceable");
      LUSH_GROUND_REPLACEABLE = register("lush_ground_replaceable");
      SMALL_DRIPLEAF_PLACEABLE = register("small_dripleaf_placeable");
      SNOW = register("snow");
      AXE_MINEABLE = register("mineable/axe");
      HOE_MINEABLE = register("mineable/hoe");
      PICKAXE_MINEABLE = register("mineable/pickaxe");
      SHOVEL_MINEABLE = register("mineable/shovel");
      NEEDS_DIAMOND_TOOL = register("needs_diamond_tool");
      NEEDS_IRON_TOOL = register("needs_iron_tool");
      NEEDS_STONE_TOOL = register("needs_stone_tool");
      FEATURES_CANNOT_REPLACE = register("features_cannot_replace");
      LAVA_POOL_STONE_REPLACEABLES = register("lava_pool_stone_replaceables");
      GEODE_INVALID_BLOCKS = register("geode_invalid_blocks");
   }
}
